// AUTO-GENERATED by source-truth/port.mjs. Do not edit by hand.
export const PORT_CSS: Record<string, string[]> = {
  "about": [
    "/port-css/wpr-733d35dcae09e8bc.css",
    "/port-css/fusion-d2adbf8047b875d1.css"
  ],
  "book-now": [
    "/port-css/wpr-80414015c121b343.css",
    "/port-css/fusion-198105efa3b541e5.css"
  ],
  "contact": [
    "/port-css/wpr-80414015c121b343.css",
    "/port-css/fusion-198105efa3b541e5.css"
  ],
  "emergency-septic-services": [
    "/port-css/wpr-b45622dbaa5d746a.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "grease-trap-service": [
    "/port-css/wpr-d78016ef1dff5c7e.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "home": [
    "/port-css/wpr-76300e01136041e3.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "post-can-a-septic-tank-freeze": [
    "/port-css/wpr-6bf857c9100aa256.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-how-does-a-septic-alarm-work": [
    "/port-css/wpr-0082630571f1519e.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-how-does-a-septic-tank-work": [
    "/port-css/wpr-6b24c53ff956985f.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-how-long-does-a-septic-inspection-take": [
    "/port-css/wpr-0082630571f1519e.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-how-often-should-you-pump-your-septic-tank-in-the-fraser-valley": [
    "/port-css/wpr-8e57eae1e8663745.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-septic-services-in-mission-common-problems-we-see": [
    "/port-css/wpr-0082630571f1519e.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-septic-tank-pumping-in-abbotsford-bc": [
    "/port-css/wpr-46de7061feb84b09.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-spring-septic-maintenance-tips": [
    "/port-css/wpr-46de7061feb84b09.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-the-importance-of-perimeter-drainage": [
    "/port-css/wpr-e11128377381f10b.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-top-3-tips-for-keep-your-septic-system-from-freezing": [
    "/port-css/wpr-c088a0f238d17885.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-top-3-tips-for-winter-septic-tank-services": [
    "/port-css/wpr-6bf857c9100aa256.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-top-5-signs-your-septic-system-needs-professional-attention": [
    "/port-css/wpr-6bf857c9100aa256.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "post-what-is-emergency-grease-trap-cleaning": [
    "/port-css/wpr-0082630571f1519e.css",
    "/port-css/fusion-9bda2795f4df247a.css"
  ],
  "septic-alarms": [
    "/port-css/wpr-aa2bb27e55cd0f34.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "septic-calculator": [
    "/port-css/wpr-0d9dc78a335b2586.css",
    "/port-css/fusion-5ce0062393317918.css"
  ],
  "septic-inspection": [
    "/port-css/wpr-aa2bb27e55cd0f34.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "septic-services-abbotsford": [
    "/port-css/wpr-4fcd6d4e9d35dee0.css",
    "/port-css/fusion-d2adbf8047b875d1.css"
  ],
  "septic-services-chilliwack": [
    "/port-css/wpr-4fcd6d4e9d35dee0.css",
    "/port-css/fusion-d2adbf8047b875d1.css"
  ],
  "septic-services-hope": [
    "/port-css/wpr-10b62c51567b453f.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "septic-services-langley": [
    "/port-css/wpr-52dd76859b7e90b4.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "septic-services-mission": [
    "/port-css/wpr-10b62c51567b453f.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "septic-tank-cleaning-langley": [
    "/port-css/wpr-0bb5911f42120aca.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "septic-tank-cleaning-mission": [
    "/port-css/wpr-14b22cc5d0254f81.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ],
  "tank-pumping": [
    "/port-css/wpr-aa2bb27e55cd0f34.css",
    "/port-css/fusion-d9c23eafcc4a0810.css"
  ]
};
